apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-certificate
spec:
  secretName: prod-secret
  issuerRef:
    # The issuer created previously
    name: prod-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'example.com'
